apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-template-values
  labels:
    fleet: testing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-template-values
  template:
    metadata:
      labels:
        app: test-template-values
        {{- with .Values.clusterLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        policy: {{ default "none" .Values.policy  | quote }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
            - sleep
            - 7d
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames: {{- range $host := .Values.hostnames }}
            -  {{ $host }}
            {{- end }}
